### ISSUE TITLE
Teleport error

### ISSUE THREAD

**Issue by williambacteria** [masagameplay/MaSuiteCore#11]
Hello! I set a warp "dp" in Plotserver, Player use /warp dp can teleport to PlotServer,but not the location what I set. I guess it's because My server has too many mods that gives client much pressure.
So I think this plugin can add a config that we can set a delay time when player change to another server.For example: Player type "/warp dp",then bungee send player to plotserver and send player to dp's location in 10s or more.
tp function too..
Bungeecord: Waterfall
Servercord: Catserver 1.12.2

**Comment by masagameplay** [comment]
Hello!
[The rewrites](https://ci.codemc.io/job/masagameplay/) (and the dev builds might too) have teleportation delay setting.

**Comment by williambacteria** [comment]
Thank you , I will try it
