### ISSUE TITLE
Rewrite permissions changed

### ISSUE THREAD

**Issue by williambacteria** [masagameplay/MaSuiteCore#12]
When I changed plugin to rewrite version,all permissions about masuite invalid.And I didn't find the new permission .

**Comment by masagameplay** [comment]
Hello,

Sorry I forgot to mention that there were permission changes. You can check the new permissions from these links [Warps](https://github.com/masagameplay/MaSuiteWarps/wiki/Permissions), [Homes](https://github.com/masagameplay/MaSuiteHomes/wiki/Permissions) and [Teleports](https://github.com/masagameplay/MaSuiteTeleports/wiki/Permissions). 

The permissions pages should be up to date and the other parts of wikis are currently under construction (and there are no wikis for Core, Chat and Portals) but I am trying to complete them as soon as possible.

**Comment by williambacteria** [comment]
Thank u bro!This plugin is niceeeee!!!!!

**Comment by masagameplay** [comment]
No problem!
