### ISSUE TITLE
Delay Teleport not work well

### ISSUE THREAD

**Issue by williambacteria** [masagameplay/MaSuiteCore#14]
When playerA use /tpa playerB from different  server, playerA will not teleport rightly to the playerB's position.I had set the Bungee's Masuite delay config.This function work well on warp command.I set delay 800 in BungeeCord\plugins\MaSuite\cofnig.yml and set delay 300 in BungeeCord\plugins\MaSuite\teleports\settings.yml and set delay 1500 in BungeeCord\plugins\MaSuite\warps\settings.yml
I used the latest version of rewrite.

**Comment by williambacteria** [comment]
When teleporter teleport to another server,this player will not teleport again to another player's location.

**Comment by masagameplay** [comment]
Hello,
Currently the teleportation delay is loaded from BungeeCord/plugins/MaSuite/config.yml, so try to increase that. If that does not help, I will look into this more.
