### ISSUE TITLE
error

### ISSUE THREAD

**Issue by axin0452** [masagameplay/MaSuiteCore#16]
Whenever a player dies and respawns, an error is generated

https://paste.ubuntu.com/p/NcXtsH9yht/

This server is running CatServer version git-CatServer-1.12.2-1b57158 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge version 14.23.5.2847)
>

**Comment by masagameplay** [comment]
Hello,

You can solve this issue by using [the dev builds (or the rewritten ones)](https://ci.codemc.io/job/masagameplay/).

**Comment by axin0452** [comment]
@masagameplay Thank you very much for your help
