### ISSUE TITLE
Mysql On Enable Connect Error

### ISSUE THREAD

**Issue by moniemntim** [masagameplay/MaSuiteCore#20]
21:31:12 [嚴重] ?|?? 09, 2020 9:31:12 ?U?? org.hibernate.Version logVersion
INFO: HHH000412: Hibernate Core {[WORKING]}

21:31:12 [嚴重] ?|?? 09, 2020 9:31:12 ?U?? org.hibernate.annotations.common.reflection.java.JavaReflectionManager <clinit>
INFO: HCANN000001: Hibernate Commons Annotations {5.1.0.Final}

21:31:13 [嚴重] [main] INFO dev.masa.masuitecore.HikariDataSource - HikariPool-1 - Starting...
21:31:13 [嚴重] [main] INFO dev.masa.masuitecore.HikariDataSource - HikariPool-1 - Start completed.
21:31:13 [嚴重] ?|?? 09, 2020 9:31:13 ?U?? org.hibernate.dialect.Dialect <init>
INFO: HHH000400: Using dialect: org.hibernate.dialect.MySQL55Dialect

21:31:14 [嚴重] ?|?? 09, 2020 9:31:14 ?U?? org.hibernate.engine.transaction.jta.platform.internal.JtaPlatformInitiator initiateService
INFO: HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]

21:31:14 [資訊] Enabled plugin MaSuiteCore version 2.0.0-SNAPSHOT by Masagameplay
21:31:14 [嚴重] [main] INFO dev.masa.masuitecore.HikariDataSource - HikariPool-2 - Starting...
21:31:14 [嚴重] [main] INFO dev.masa.masuitecore.HikariDataSource - HikariPool-2 - Start completed.
21:31:14 [嚴重] ?|?? 09, 2020 9:31:14 ?U?? org.hibernate.dialect.Dialect <init>
INFO: HHH000400: Using dialect: org.hibernate.dialect.MySQL55Dialect

21:31:14 [嚴重] ?|?? 09, 2020 9:31:14 ?U?? org.hibernate.engine.transaction.jta.platform.internal.JtaPlatformInitiator initiateService
INFO: HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]

**Comment by masagameplay** [comment]
Hello,

These are not error messages, they just inform that connection has succeed.

The messages should be hidden in the final builds when everything is ready to be released.
