### ISSUE TITLE
Homes with similar names not working

### ISSUE THREAD

**Issue by nzminecraftDOTcom** [masagameplay/MaSuiteCore#26]
Example
Home named ironfarm
Home named iron

I can not teleport to the home named iron as the game attempts to autocomplete to "ironfarm" thus the home iron is not available.
Setting a home named ironblock allows me to go, however if I was to set a home named ironblocktop and attempt to teleport to ironblocktop I would be taken to ironblock as it is the first home that the tab-complete would accept. 
Clicking the home in /homes does not make any difference.

**Comment by masagameplay** [comment]
This should be fixed in the next Spigot release (2.0.3).

Please note: this is a wrong repo. You should've used the MaSuiteHomes repo :P
