### ISSUE TITLE
Compatibility Bug with snap.

### ISSUE THREAD

**Issue by masterblaster221** [masagameplay/MaSuiteCore#32]
https://github.com/Phoenix616/Snap/issues/17

Fix this please.

**Comment by masterblaster221** [comment]
Well... still no reply...

**Comment by masagameplay** [comment]
Sorry, I actually tried to solve this issue but I could not find the solution for this problem without breaking old config files. Until BungeeCord has a method to change plugin folder location, this cannot be fixed.
